### ISSUE TITLE
truncation of data in colf?

### ISSUE THREAD

**Issue by dpringle** [LyzandeR/colf#1]
Oops, this was user error. Removed.

**Comment by LyzandeR** [comment]
No problem, glad you solved it.

**Comment by dpringle** [comment]
Hello Theo

Ha ha colf issue #1 is solved!

The problem was NA values in a column of my data frame. I didn't realise at first because this column was not used in the fit. I don't know if the truncation was on inputs or outputs, but for me this is solved.

Thanks for the great package, it definitely solved a work problem for me!

Cheers
Dan
